export interface empresa{
    emp_cnpj: string,
    ID_empresa: number,
    emp_nome : string,
    emp_nome_fantasia : string,
    emp_data : string,
    emp_logradouro : string,
    emp_numero : string,
    emp_complemento : string,
    emp_cep : string,
    emp_bairro : string,
    emp_municipio : string,
    emp_uf: string,
    emp_telefone : string,
    emp_imagem : string,
    emp_logomarca_claro : string,
    emp_logomarca_escuro : string,
    emp_ie: string,
    emp_im: string,
}