/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import controller.ControllerEmpresa;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import model.ModelEmpresa;


/**
 *
 * @author andre
 */
public class ViewPrincipal extends javax.swing.JFrame {
    ControllerEmpresa controllerEmpresa = new ControllerEmpresa();
    ModelEmpresa modelEmpresa = new ModelEmpresa();
    

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        carregarFundoDeTela();
        setLocationRelativeTo(null);
        jbCompras.setVisible(false);
        jbFornecedores.setVisible(false);
        jbUsuarios.setVisible(false);
        jMenu4.setVisible(false);
        jmiUsuarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFundo = new javax.swing.JPanel();
        jbClientes = new javax.swing.JButton();
        jbProdutos = new javax.swing.JButton();
        jbVendas = new javax.swing.JButton();
        jbUsuarios = new javax.swing.JButton();
        jbPDV = new javax.swing.JButton();
        jbCompras = new javax.swing.JButton();
        jbFornecedores = new javax.swing.JButton();
        jlFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiCompras = new javax.swing.JMenuItem();
        jmiFornecedores = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiConf = new javax.swing.JMenuItem();
        jmiAtualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENDAS");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jpFundo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jpFundo.setLayout(null);

        jbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/users.png"))); // NOI18N
        jbClientes.setText("CLIENTES");
        jbClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });
        jpFundo.add(jbClientes);
        jbClientes.setBounds(10, 11, 150, 31);

        jbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/database.png"))); // NOI18N
        jbProdutos.setText("PRODUTOS");
        jbProdutos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutosActionPerformed(evt);
            }
        });
        jpFundo.add(jbProdutos);
        jbProdutos.setBounds(10, 90, 150, 31);

        jbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/shopping_cart.png"))); // NOI18N
        jbVendas.setText("VENDAS");
        jbVendas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendasActionPerformed(evt);
            }
        });
        jpFundo.add(jbVendas);
        jbVendas.setBounds(10, 50, 150, 31);

        jbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/user.png"))); // NOI18N
        jbUsuarios.setText("USUÁRIOS");
        jbUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosActionPerformed(evt);
            }
        });
        jpFundo.add(jbUsuarios);
        jbUsuarios.setBounds(10, 250, 150, 31);

        jbPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/promotion.png"))); // NOI18N
        jbPDV.setText("PDV");
        jbPDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPDVActionPerformed(evt);
            }
        });
        jpFundo.add(jbPDV);
        jbPDV.setBounds(10, 130, 150, 31);

        jbCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/dollar_currency_sign.png"))); // NOI18N
        jbCompras.setText("COMPRAS");
        jbCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprasActionPerformed(evt);
            }
        });
        jpFundo.add(jbCompras);
        jbCompras.setBounds(10, 170, 150, 31);

        jbFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/promotion.png"))); // NOI18N
        jbFornecedores.setText("FORNECEDORES");
        jbFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedoresActionPerformed(evt);
            }
        });
        jpFundo.add(jbFornecedores);
        jbFornecedores.setBounds(10, 210, 150, 31);

        jlFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlFundo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlFundoFocusGained(evt);
            }
        });
        jpFundo.add(jlFundo);
        jlFundo.setBounds(10, 0, 803, 550);

        jMenu1.setText("Arquivo");

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/16x16/exit.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jMenu2.add(jmiClientes);

        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiProdutos);

        jmiUsuarios.setText("Usuários");
        jmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUsuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmiVendas.setText("Vendas");
        jmiVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jmiVendas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Compras");

        jmiCompras.setText("Compras");
        jmiCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComprasActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCompras);

        jmiFornecedores.setText("Fornecedores");
        jmiFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedoresActionPerformed(evt);
            }
        });
        jMenu4.add(jmiFornecedores);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Opções");

        jmiConf.setText("Configurações");
        jmiConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConfActionPerformed(evt);
            }
        });
        jMenu5.add(jmiConf);

        jmiAtualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jmiAtualizar.setText("Atualizar");
        jmiAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAtualizarActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAtualizar);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        // TODO add your handling code here:
        new ViewPessoa().setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        // TODO add your handling code here:
        new viewProduto().setVisible(true);
    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuariosActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jmiUsuariosActionPerformed

    private void jmiVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendasActionPerformed
        // TODO add your handling code here:
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jmiVendasActionPerformed

    private void jbPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPDVActionPerformed
        try {
            // TODO add your handling code here:
            new viewPDV().setVisible(true);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPDVActionPerformed

    private void jbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosActionPerformed
        // TODO add your handling code here:
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_jbUsuariosActionPerformed

    private void jbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendasActionPerformed
        // TODO add your handling code here:
        new ViewVendas().setVisible(true);
    }//GEN-LAST:event_jbVendasActionPerformed

    private void jbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutosActionPerformed
        // TODO add your handling code here:
        new viewProduto().setVisible(true);
    }//GEN-LAST:event_jbProdutosActionPerformed

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        // TODO add your handling code here:
        new ViewPessoa().setVisible(true);
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jmiComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComprasActionPerformed
        // TODO add your handling code here:
        new ViewCompras().setVisible(true);
    }//GEN-LAST:event_jmiComprasActionPerformed

    private void jmiFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedoresActionPerformed
        // TODO add your handling code here:
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jmiFornecedoresActionPerformed

    private void jbComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprasActionPerformed
        // TODO add your handling code here:
        new ViewCompras().setVisible(true);
    }//GEN-LAST:event_jbComprasActionPerformed

    private void jbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedoresActionPerformed
        // TODO add your handling code here:
        new ViewFornecedor().setVisible(true);
    }//GEN-LAST:event_jbFornecedoresActionPerformed

    private void jmiConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConfActionPerformed
        try {
            // TODO add your handling code here:
            new ViewEmpresa().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiConfActionPerformed

    private void jlFundoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlFundoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jlFundoFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jmiAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAtualizarActionPerformed
        // TODO add your handling code here:
        carregarFundoDeTela();
    }//GEN-LAST:event_jmiAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewPrincipal().setVisible(true);
        });
    }
    
    private void carregarFundoDeTela(){
        modelEmpresa = controllerEmpresa.getEmpresaController(1);
        
        String imagem = "http://localhost:3001/getdataimage/sistema/" + modelEmpresa.getEmp_imagem();
        URL imagemUrl = null;
        try {
            imagemUrl = new URL(imagem);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon imagemBg = new ImageIcon(imagemUrl); 
        
        //ImageIcon imagemBg = new ImageIcon(modelEmpresa.getEmp_imagem()); 
        Image imageA = imagemBg.getImage(); 
        Image newimgA = imageA.getScaledInstance(jlFundo.getWidth(), jlFundo.getHeight(), Image.SCALE_DEFAULT); 
        imagemBg = new ImageIcon(newimgA);  
        jlFundo.setIcon(imagemBg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbCompras;
    private javax.swing.JButton jbFornecedores;
    private javax.swing.JButton jbPDV;
    private javax.swing.JButton jbProdutos;
    private javax.swing.JButton jbUsuarios;
    private javax.swing.JButton jbVendas;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JMenuItem jmiAtualizar;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiCompras;
    private javax.swing.JMenuItem jmiConf;
    private javax.swing.JMenuItem jmiFornecedores;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiUsuarios;
    private javax.swing.JMenuItem jmiVendas;
    private javax.swing.JPanel jpFundo;
    // End of variables declaration//GEN-END:variables
}
